#!/bin/bash
say YOU HAVE BEEN HACKED BY DREWMAL
sleep 3
say YOU HAVE BEEN HACKED BY DREWMAL
sleep 3
say YOU HAVE BEEN HACKED BY DREWMAL
sleep 3
say YOU HAVE BEEN HACKED BY DREWMAL
sleep 3
say YOU HAVE BEEN HACKED BY DREWMAL
sleep 3
say YOU HAVE BEEN HACKED BY DREWMAL
sudo cp /volumes/hacktop/main.sh /bin/emmc
sudo emmc
